set nocompatible
" A tab has 4 spaces long
set tabstop=4
set shiftwidth=4

" Vim5 and later versions support syntax highlighting. Uncommenting the next
" line enables syntax highlighting by default.
if &t_Co >= 256 || has("gui_running")
	colorscheme mustang
endif

if &t_Co > 2 || has("gui_running")
	" switch syntax highlighting on, when the terminal has colors
	syntax on
endif

" If using a dark background within the editing area and syntax highlighting
" turn on this option as well
set background=dark

" Uncomment the following to have Vim jump to the last position when
" reopening a file
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

" Uncomment the following to have Vim load indentation rules and plugins
" according to the detected filetype.
if has("autocmd")
  filetype plugin indent on
endif

" The following are commented out as they cause vim to behave a lot
" differently from regular Vi. They are highly recommended though.
"set showcmd		" Show (partial) command in status line.
set showmatch		" Show matching brackets.
"set ignorecase		" Do case insensitive matching
set smartcase		" Do smart case matching
set incsearch		" Incremental search
"set autowrite		" Automatically save before commands like :next and :make
"set hidden             " Hide buffers when they are abandoned
"set mouse=a		" Enable mouse usage (all modes)

" Source a global configuration file if available
if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif


" Set a vertical line on the 81st column
set number
set tw=79
set colorcolumn=81
highlight ColorColumn ctermbg=233



" Reselect visual block after indent/outdent
vnoremap < <gv
vnoremap > >gv

"Easy split navigation
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" Automatically reload vimrc when it's saved
au BufWritePost .vimrc so ~/.vimrc

" Clear search highlights
" noremap <silent><Leader>/ :nohls<CR>

" Turn off arrows keys
nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
inoremap <up> <nop>
inoremap <down> <nop>
inoremap <left> <nop>
inoremap <right> <nop>

" Highlight trailing white-space(s)
highlight WhitespaceEOL ctermbg=Red guibg=Red
match WhitespaceEOL /\s\+$/

" Ignore F1 key
inoremap <F1> <nop>
nnoremap <F1> <nop>
vnoremap <F1> <nop>

call pathogen#infect()

" Some NERDTree configurations
" 0. Toggle NERDTree view with ctrl + N
nmap <silent> <c-n> :NERDTreeToggle<CR>

" 1. Open NERDTree automatically when vim starts up without a file being
" specified
autocmd vimenter * if !argc() | NERDTree | endif

" 2. Close Vim if the only window open is a NERDTree
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTRreeType") && b:NERDTreeType == "primary") | q | endif

" More hints on www.vimbits.com ;)


